# Auto-merge Allowlist for Pin Upgrade PRs
#
# This file controls which servers are eligible for automatic merging when
# their pin upgrade PRs pass all required checks.
#
# Only add servers to this list after verifying they meet these criteria:
# - Stable build process with consistent success rate
# - Comprehensive test coverage
# - Low risk of breaking changes from upstream updates
# - Active monitoring of build failures
#
# To add a server to the allowlist:
# 1. Verify the server has had stable builds for at least 2 weeks
# 2. Review recent pin update PRs for any issues
# 3. Add the server name to the list below
# 4. Monitor the first few auto-merges closely
#
# To block auto-merge for a specific PR, add the 'skip-auto-merge' label

servers:
  # Start with a small, conservative list of stable servers
  # Expand gradually based on monitoring results

  # Well-established, stable servers with consistent successful builds
  - fibery
