version: "3"

tasks:
  create:
    desc: Create a new mcp server definition
    cmd: go run ./cmd/create {{.CLI_ARGS}}

  catalog:
    desc: Generate a test catalog
    cmd: go run ./cmd/catalog {{.CLI_ARGS}}