name: prometheus-mcp-server
image: ghcr.io/tjhop/prometheus-mcp-server
type: server
meta:
  category: database
  tags:
    - database
    - metrics
    - monitoring
    - observability
    - prometheus
about:
  title: Prometheus MCP server
  description: "A Prometheus MCP server with full API support for comprehensive management and deep interaction with Prometheus beyond basic query support. Written in go, it is a single binary install that is capable of STDIO, SSE, and HTTP transports for complex deployments."
  icon: mcp/prometheus-mcp-server
source:
  project: https://github.com/tjhop/prometheus-mcp-server
