name: netlify
type: remote
dynamic:
  tools: true
meta:
  category: devops
  tags:
    - devops
    - hosting
    - deployment
    - remote
about:
  title: Netlify
  description: Deploy and host web applications with continuous deployment, serverless functions, and global CDN
  icon: https://www.google.com/s2/favicons?domain=netlify.com&sz=64
remote:
  transport_type: streamable-http
  url: https://netlify-mcp.netlify.app/mcp
oauth:
  - provider: netlify
    secret: netlify.personal_access_token
    env: NETLIFY_PERSONAL_ACCESS_TOKEN
