build:
  name: Build
  runs-on: ubuntu-latest
  strategy:
    fail-fast: false   # <--- ปิดการยกเลิกทั้งชุดเมื่อมีตัวใดตัวหนึ่ง fail
    matrix:
      go-version: [ '1.22.x', '1.23.x', '1.24.x' ]
  steps:
    - uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    - run: go mod download
    - run: go build -v ./...
